clc
clear all;
%程序用于读取雷达的dzt数据
fid=fopen('FILE____035 P_11.DZT','rb');%打开文件，参考资料http://www.doc88.com/p-9089711434820.html
rh.tag=fread(fid,1,'ushort');
rh.data=fread(fid,1,'ushort');
rh.nsamp=fread(fid,1,'ushort');
rh.bits=fread(fid,1,'ushort');
rh.zero=fread(fid,1,'short');
rh.sps=fread(fid,1,'float');
rh.spm=fread(fid,1,'float');
rh.mpm=fread(fid,1,'float');
rh.position=fread(fid,1,'float');
rh.range=fread(fid,1,'float');
rh.npass=fread(fid,1,'ushort');
%读取DztDataStruct结构
Create.sec2=fread(fid,1,'ubit5');
Create.min=fread(fid,1,'ubit6');
Create.hour=fread(fid,1,'ubit5');
Create.day=fread(fid,1,'ubit5');
Create.month=fread(fid,1,'ubit4');
Create.year=fread(fid,1,'ubit7');
Modify.sec2=fread(fid,1,'ubit5');
Modify.min=fread(fid,1,'ubit6');
Modify.hour=fread(fid,1,'ubit5');
Modify.day=fread(fid,1,'ubit5');
Modify.month=fread(fid,1,'ubit4');
Modify.year=fread(fid,1,'ubit7');
rh.ragain=fread(fid,1,'ushort');
rh.nrgain=fread(fid,1,'ushort');
rh.text=fread(fid,1,'ushort');
rh.ntext=fread(fid,1,'ushort');
rh.proc=fread(fid,1,'ushort');
rh.nproc=fread(fid,1,'ushort');
rh.nchan=fread(fid,1,'ushort');
rh.epsr=fread(fid,1,'float');
rh.top=fread(fid,1,'float');
rh.depth=fread(fid,1,'float');
reserve=fread(fid,1,'char');
rh.spp=fread(fid,1,'ushort');
rh.linenum=fread(fid,1,'ushort');
rh.startx=fread(fid,1,'short');
rh.starty=fread(fid,1,'short');
rh.endx=fread(fid,1,'short');
rh.endy=fread(fid,1,'short');
rh.lineorder=fread(fid,1,'char');
rh.dtype=fread(fid,1,'char');
rh.antname=fread(fid,1,'char');
rh.chanmask=fread(fid,1,'ushort');
rh.name=fread(fid,1,'char');
rh.chksum=fread(fid,1,'short');
rh.variable=fread(fid,1,'char');
% rh.comments=setchar(fread(fid,[rh.ntext inf],'char'));
rh.processing=fread(fid,rh.nproc,'char');
fseek(fid,1024,'bof');%从文件头尾部开始读取数据
d=fread(fid,[rh.nsamp inf],'ushort');%读取数据
fclose(fid);